# Generated by Django 5.1.6 on 2025-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
